name: unicorn_binance_rest_api

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.9
  - certifi>=2025.6.15
  - colorama
  - cryptography>=45.0.4
  - cython
  - dateparser
  - pyopenssl
  - pysocks
  - requests>=2.32.4
  - regex
  - pip:
    - service-identity
