blank_issues_enabled: true
contact_links:
  - name: UNICORN Devs Chat
    url: https://t.me/unicorndevs
    about: Chat to us about the UNICORN Binance REST API and ask general questions.
  - name: UNICORN Binance REST API Discussions
    url: https://github.com/oliver-zehentleitner/unicorn-binance-rest-api/discussions
    about: Ask general questions.
  - name: UNICORN Binance REST API documentation
    url: https://oliver-zehentleitner.github.io/unicorn-binance-rest-api/
    about: The complete UNICORN Binance REST API documentation.

